#!/bin/bash
set -eu
set -o pipefail

mkdir -p /var/lib/cloud/scripts/per-instance/
SCRIPT=/var/lib/cloud/scripts/per-instance/10-start-cwl-docker
cat > $SCRIPT <<EOT
#!/bin/bash
docker run -d --restart=always -p 80:80 nginx:latest
EOT

chmod +x $SCRIPT
